myWebApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'myapp/', include('myapp.urls')),
]

myapp/urls.py
from django.urls import path
from myapp import views

app_name = 'myapp'
urlpatterns = [
    path(r'login/', views.user_login, name='login'),
    path(r'logout/', views.user_logout, name='logout'),
    path(r'gallery', views.gallery, name='gallery'),
    path(r'gallery/add', views.addPhoto, name='addPhoto'),
    path(r'gallery/<int:pno>', views.viewPhoto, name='viewPhoto'),
    path(r'gallery/delete/<int:pno>', views.deletePhoto, name='deletePhoto'),
]

myapp/models.py
# from django.core.exceptions import ValidationError
# from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.contrib.auth.models import User



class Student(User):
    CITY_CHOICES = [('WS', 'Windsor'), ('CG', 'Calgary'), ('MR', 'Montreal'), ('VC', 'Vancouver')]
    school = models.CharField(max_length=50, null=True, blank=True)
    city = models.CharField(max_length=2, choices=CITY_CHOICES, default='WS')
    image = models.ImageField(null=True, blank=True, upload_to='images/')

    def __str__(self):
        return self.first_name + " " + self.last_name


class Photo(models.Model):
    image = models.ImageField(upload_to='images/')
    label = models.CharField(blank=True, max_length=100)
    student = models.ForeignKey(Student, related_name='gallery', on_delete=models.CASCADE)
    favourite = models.BooleanField(default=False)

myapp/forms.py
from django import forms
from myapp.models import Student, Photo


class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ['label', 'favourite', 'image']

        widgets = {
            'label': forms.TextInput({'class': 'form-control'})
        }


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['first_name', 'last_name', 'username',
                  'email', 'password', 'school',
                  'city', 'image']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control'}),
            'school': forms.TextInput(attrs={'class': 'form-control'}),
            'city': forms.Select(attrs={'class': 'form-control'}),
        }

myapp/views.py
import random
import string
from datetime import datetime

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse

from .forms import StudentForm, PhotoForm
from .models import Student, Photo


# Create your views here.
@login_required
def gallery(request):
    student = Student.objects.get(pk=request.user.id)
    photos = Photo.objects.filter(student=student)
    context = {'photos': photos}
    return render(request, 'myapp/gallery.html', context)


@login_required
def addPhoto(request):
    if request.method == 'POST':
        form = PhotoForm(request.POST, request.FILES or None)
        if form.is_valid():
            photo = form.save(commit=False)
            photo.student = Student.objects.get(pk=request.user.id)
            photo.save()
            form.save_m2m()
            context = {'response': 'Photo Uploaded'}
            return render(request, 'myapp/generic_response.html', context)
        else:
            context = {'response': 'Error occurred, trt again letter'}
            return render(request, 'myapp/generic_response.html', context)
    else:
        form = PhotoForm()
        context = {'form': form}
        return render(request, 'myapp/addPhoto.html', context)


def viewPhoto(request, pno):
    try:
        photo = Photo.objects.get(pk=pno)
        if request.method == 'POST':
            form = PhotoForm(request.POST, request.FILES or None, instance=photo)
            context = {'form': form, 'photo': photo}

            if form.is_valid():
                photo = form.save(commit=False)
                photo.student = Student.objects.get(pk=request.user.id)
                photo.save()
                form.save_m2m()
                context = {'response': 'Photo Updated'}
                return render(request, 'myapp/generic_response.html', context)
            else:
                context = {'response': 'Error occurred, trt again letter'}
                return render(request, 'myapp/generic_response.html', context)
        else:
            form = PhotoForm(instance=photo)
            context = {'form': form, 'photo':photo}
            return render(request, 'myapp/viewPhoto.html', context)

    except Photo.DoesNotExist:
        context = {'response': 'Page not found'}
        return render(request, 'myapp/generic_response.html', context)


def deletePhoto(request, pno):
    try:
        photo = Photo.objects.get(pk=pno)
        photo.delete()
        context = {'response': 'Photo Deleted'}
        return render(request, 'myapp/generic_response.html', context)
    except Photo.DoesNotExist:
        context = {'response': 'Page not found'}
        return render(request, 'myapp/generic_response.html', context)



def user_login(request):
    if request.user.is_authenticated:
        return redirect('myapp:part2_index')
    if request.method == 'POST':
        # if request.session.test_cookie_worked():
        #     request.session.delete_test_cookie()
        #     print("test cookie worked")
        # else:
        #     print("test cookie didn't work")
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                request.session['last_login'] = datetime.now().strftime("%H:%M:%S - %B %d, %Y")
                request.session.set_expiry(3600)
                if request.POST.get('next') != '':
                    return redirect(request.POST.get('next'))
                return HttpResponseRedirect(reverse('myapp:gallery'))
            else:
                return HttpResponse('Your account is disabled.')
        else:
            return HttpResponse('Invalid login details.')
    else:
        # request.session.set_test_cookie()
        return render(request, 'myapp/login.html')


@login_required
def user_logout(request):
    logout(request)
    # request.session.flush()
    # for key in list(request.session.keys()):
    #     del request.session[key]
    return HttpResponseRedirect(reverse('myapp:gallery'))



def register(request):
    if request.method == 'POST':
        form = StudentForm(request.POST, request.FILES or None)
        if form.is_valid():
            student = form.save(commit=False)
            student.set_password(student.password)
            student.save()
            form.save_m2m()

            msg = 'Congratulations, You are now registered as a student'
            return render(request, 'myapp/register_response.html', {'msg': msg})
    else:
        form = StudentForm()
    return render(request, 'myapp/register.html', {'form': form})

myapp/templates/myapp/addPhoto.html
{% extends 'myapp/pbase.html' %}
{% block body_block %}
    <div class="container">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token%}
            <div class="container">
            {{ form.as_p }}
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
{% endblock %}

myapp/templates/myapp/gallery.html
{% extends 'myapp/pbase.html' %}
{% block body_block %}
    <br/>
    <div class="container">
        <table id="photoTable" style="width:20%">
            <thead>
            <th></th>
            </thead>
        <tbody>
            {% if photos %}
            {% for photo in photos %}
                <tr>
                    <td>
                        <div class="card" style="width: 18rem;">
                            {% if photo.favourite %}
                            <div class="card-header text-center">
                                Favourite
                            </div>
                            {% endif %}
                            <img class="card-img-top" src="{{ photo.image.url }}" alt="Card image cap">
                                <div class="card-body">
                                    <h5 class="card-title">{{ photo.label }}</h5>
{#                                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>#}
                                    <a href="{% url "myapp:viewPhoto" photo.id %}" class="btn btn-primary">View</a>
                                </div>
                        </div>
                    </td>
                </tr>
            {% endfor %}
            {% endif %}
        </tbody>
        </table>
    </div>
<script>
    $(document).ready(function () {
       $('#photoTable').DataTable({
           pageLength:1,
           lengthMenu: [[1,2, 5, 10], [1,2, 5, 10]],
       })
    });
</script>
{% endblock %}

myapp/templates/myapp/generic_response.html
{% extends 'myapp/pbase.html' %}

{% block body_block %}
    <strong>{{ response }}</strong>

{% endblock %}

myapp/templates/myapp/login.html
{% extends 'myapp/pbase.html' %}
{% block body_block %}
    <div style="width: 80%; margin: auto">
      <form method="post">
        {% csrf_token%}
        <div class="mb-3">
          <label for="exampleInputEmail1" class="form-label">Username</label>
          <input type="text" name="username" class="form-control" />
        </div>
        <div class="mb-3">
          <label for="exampleInputPassword1" class="form-label">Password</label>
          <input type="password" name="password" class="form-control" />
        </div>

        <input type="hidden" name="next" value="{{ request.GET.next }}">
        <button type="submit" class="btn btn-primary">Login</button>
{#        <div class="row mb-4">#}
{#            <div class="col">#}
{#                <a href="{% url 'myapp:reset_password' %}">Forgot Password</a>#}
{#            </div>#}
{#        </div>#}
      </form>
    </div>
{% endblock %}

myapp/templates/myapp/pbase.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}"/>
        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css">
        <!-- CSS only -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
        <script type="text/javascript" src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>
        <!-- JavaScript Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
        <title>Online Store APP - {% block title %}Welcome!{% endblock %}</title>
    </head>
    <body>
        <div class="container">
            <header class="d-flex flex-wrap justify-content-center border-bottom">
                <a href="{% url 'myapp:gallery' %} " class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
                    <span class="fs-4">{% block myhdg %}Hello {{ request.user.first_name }}{% endblock %}</span>
                </a>
                <ul class="nav nav-pills">
                {% if request.user.is_authenticated %}
                <li class="nav-item"><a href="{% url 'myapp:addPhoto' %}" class="nav-link">Add Photo</a></li>
                <li class="nav-item"><a href="{% url 'myapp:logout' %}" class="nav-link">Logout</a></li>
                {% else %}
                <li class="nav-item"><a href="{% url 'myapp:login' %}" class="nav-link">Login</a></li>
                {% endif %}
            </ul>
            </header>
        </div>

        <div class="container">
        {% block body_block %}*** {% endblock %}
        </div>
        <div class="container">
        <footer class="py-3 my-4">
            <ul class="nav justify-content-center border-bottom pb-3 mb-3">
            <li class="nav-item"><a href = "{% url 'myapp:gallery' %}" class="nav-link px-2 text-muted">Home</a><br/></li>
            </ul>
            <p class="text-center text-muted">© Internship Project 1</p>
        </footer>
        </div>
    </body>
</html>

myapp/templates/myapp/viewPhoto.html
{% extends 'myapp/pbase.html' %}
{% block body_block %}
    <div class="container">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token%}
            <div class="container">
            <div class="card" style="width: 30rem;">
                <img class="card-img-top" src="{{ photo.image.url }}" alt="Card image cap">
            </div>
            <br/>
            {{ form.as_p }}
            </div>
            <button type="submit" class="btn btn-primary">Update</button>
            <button type="button" class="btn btn-danger" onclick="location.href='{% url "myapp:deletePhoto" photo.id %}'">Delete</button>
        </form>
    </div>
{% endblock %}